version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api-cloudtrim"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-129db3hpi88as"
s3_prefix = "api-cloudtrim"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

